spring:
  application:
    name: libraryapi
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #none and create-drop
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_ID}
            client-secret: ${OAUTH2_SECRET}
springdoc:
  override-with-generic-response: false
logging:
  file:
    name: app.log